#!/bin/bash

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --py jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy
jupyter lab build

code-server --install-extension ms-python.python

# Install the VS code proxy
pip install -e.

# Install conda packages
conda install -n notebook pylint flake8 pytest pylint black -Y

chmod a+w -R /srv/conda/envs
